const resList = [
    {
            data: {
                uuid: "def456-7890-ghij-slmn-oddrstuvwx",
                name: "Burger Lab",
                cloudinaryImageId: "https://play-lh.googleusercontent.com/soPvnOP8W0BRDPfqJPZB577ATZj44sjTqzp-STXq9iRNDKu0rgAmq49xikglqrUE7N4",
                cuisines: ["Burger", "Pizza"],
                costForTwo: 1200,
                deliveryTime: 40,
                avgRating: "3.9",
            },
        },
        {
            data: {
                uuid: "def456-7890-ghej-slmn-opqrstuvwx",
                name: "Domino's Pizza",
                cloudinaryImageId: "https://www.investopedia.com/thmb/g59VZZdx_gfVS5XUzMhIdN1M_dc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1992180265-ed0b69a9a1484e47be1edf93362ec650.jpg",
                cuisines: ["Burger", "Pizza"],
                costForTwo: 1200,
                deliveryTime: 40,
                avgRating: "4.5",
            },
        },
        {
            data: {
                uuid: "def456-7890-ghwj-slmn-opqrstuvwx",
                name: "MCDonald's",
                cloudinaryImageId: "https://www.investopedia.com/thmb/a_tD7rBwlEFRJGL-yuZnbE7lnZY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/shutterstock_523483492-mcdonalds-5988b1ffc412440010f2d0b9.jpg",
                cuisines: ["Burger", "Pizza","pasta"],
                costForTwo: 1100,
                deliveryTime: 40,
                avgRating: "4.1",
            },
        },
    {
    type: "restaurant",
    data: {
        type: "F",
        id: "12345",
        name: "Meghana Food",
        uuid: "1234-5678-91011",
        city: "Bangalore",
        area: "Koramangala",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/g0isknuhld1ltwxkjkcg",
        cuisines: ["Biryani", "North Indian", "Asian"],
        tags: [],
        costForTwo: 500,
        costForTwoString: "₹500 for two",
        deliveryTime: 30,
        minDeliveryTime: 25,
        maxDeliveryTime: 35,
        lastMileTravel: 2.5,
        slugs: {
            restaurant: "meghana-food-koramangala",
            city: "bangalore"
        },
        cityState: "1",
        address: "123, Street Name, Koramangala, Bangalore",
        locality: "Koramangala",
        parentId: 1234,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        avgRating: "4.5",
        totalRatings: 1000,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
            header: "50% off",
            shortDescriptionList: [
                {
                    meta: "50% off | Use code SWIGGY50",
                    discountType: "Percentage",
                    operationType: "RESTAURANT"
                }
            ],
            descriptionList: [
                {
                    meta: "50% off up to ₹100 | Use code SWIGGY50",
                    discountType: "Percentage",
                    operationType: "RESTAURANT"
                }
            ],
            subHeader: "",
            headerType: 0,
            superFreedel: ""
        },
        
    }
},
{
    type: "restaurant",
    data: {
        type: "F",
        id: "67890",
        name: "KFC",
        uuid: "1234-5678-91012",
        city: "Bangalore",
        area: "Indiranagar",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "https://cms-tpq.theparq.com/wp-content/uploads/2020/07/AW_NEW-KFC-LOGO-2019-1024x724.jpg",
        cuisines: ["Burger", "Fast Food"],
        tags: [],
        costForTwo: 600,
        costForTwoString: "₹600 for two",
        deliveryTime: 40,
        minDeliveryTime: 35,
        maxDeliveryTime: 45,
        lastMileTravel: 3.0,
        slugs: {
            restaurant: "kfc-indiranagar",
            city: "bangalore"
        },
        cityState: "1",
        address: "456, Street Name, Indiranagar, Bangalore",
        locality: "Indiranagar",
        parentId: 5678,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        avgRating: "4.2",
        totalRatings: 500,
    }
},
{
    type: "restaurant",
    data: {
        type: "F",
        id: "11223",
        name: "Pizza Hut",
        uuid: "1234-5678-91013",
        city: "Bangalore",
        area: "MG Road",
        totalRatingsString: "2000+ ratings",
        cloudinaryImageId: "https://images-prd.sodexomyway.net/web/en-us/media/pizza-hut-new-retro-logo-promo_tcm17-28208.png",
        cuisines: ["Pizza", "Italian"],
        tags: [],
        costForTwo: 800,
        costForTwoString: "₹800 for two",
        deliveryTime: 45,
        minDeliveryTime: 40,
        maxDeliveryTime: 50,
        lastMileTravel: 4.0,
        slugs: {
            restaurant: "pizza-hut-mg-road",
            city: "bangalore"
        },
        cityState: "1",
        address: "789, Street Name, MG Road, Bangalore",
        locality: "MG Road",
        parentId: 91011,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        avgRating: "4.8",
        totalRatings: 2000,
    }
},
{
    type: "restaurant",
    data: {
        type: "F",
        id: "33445",
        name: "Sushi House",
        uuid: "1234-5678-91014",
        city: "Bangalore",
        area: "Jayanagar",
        totalRatingsString: "300+ ratings",
        cloudinaryImageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBXfmVSasohMAD-ovnA9hvWWAJPpuSGSzOXA&s",
        cuisines: ["Japanese", "Sushi"],
        tags: [],
        costForTwo: 1000,
        costForTwoString: "₹1000 for two",
        deliveryTime: 50,
        minDeliveryTime: 45,
        maxDeliveryTime: 55,
        lastMileTravel: 5.0,
        slugs: {
            restaurant: "sushi-house-jayanagar",
            city: "bangalore"
        },
        cityState: "1",
        address: "101, Street Name, Jayanagar, Bangalore",
        locality: "Jayanagar",
        parentId: 121314,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        avgRating: "4.6",
        totalRatings: 300,
    }
},
{
    type: "restaurant",
    data: {
        type: "F",
        id: "789012",
        name: "Pizza Palace",
        uuid: "def456",
        city: "1",
        area: "Indiranagar",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPU57JQpv3vkFX96OWBf6aS2v-gnkYgnDGnQ&s",
        cuisines: ["Italian", "Pizza"],
        tags: [],
        costForTwo: 800,
        costForTwoString: "₹800 for two",
        deliveryTime: 30,
        minDeliveryTime: 25,
        maxDeliveryTime: 35,
        lastMileTravel: 3.5,
        slugs: {
            restaurant: "pizza-palace-indiranagar",
            city: "bangalore"
        },
        cityState: "1",
        address: "202, Street Name, Indiranagar, Bangalore",
        locality: "Indiranagar",
        parentId: 567890,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        avgRating: "4.8",
        totalRatings: 500,
    }
},
{
    type: "restaurant",
    data: {
        type: "F",
        id: "789012",
        name: "Sushi World",
        uuid: "def456-7890-ghij-klmn-opqrstuvwx",
        city: "2",
        area: "Downtown",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiXrDJOl6eWKkg0Z3a4331k6t26Y885Evn0A&s",
        cuisines: ["Japanese", "Sushi"],
        tags: [],
        costForTwo: 1200,
        costForTwoString: "₹1200 for two",
        deliveryTime: 40,
        minDeliveryTime: 35,
        maxDeliveryTime: 45,
        lastMileTravel: 4.0,
        slugs: {
            restaurant: "sushi-world-downtown",
            city: "newyork"
        },
        cityState: "2",
        address: "303, Sushi Street, Downtown, New York",
        locality: "Downtown",
        parentId: 678901,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        avgRating: "4.5",
        totalRatings: 150,
    }
},
{
    type: "restaurant",
    data: {
        type: "F",
        id: "789012",
        name: "Burger King",
        uuid: "def456-7890-ghij-klmn-opqrstuvdx",
        city: "2",
        area: "Downtown",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "https://cdn.prod.website-files.com/5ee732bebd9839b494ff27cd/5ef0a3d4299cb9f4f7ea67c4_Burger-King-Logo.png",
        cuisines: ["Burger", "Fast Food"],
        tags: [],
        costForTwo: 1200,
        costForTwoString: "₹1200 for two",
        deliveryTime: 40,
        minDeliveryTime: 35,
        maxDeliveryTime: 45,
        lastMileTravel: 4.0,
        slugs: {
            restaurant: "sushi-world-downtown",
            city: "newyork"
        },
        cityState: "2",
        address: "303, Sushi Street, Downtown, New York",
        locality: "Downtown",
        parentId: 678901,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        avgRating: "3.8",
        totalRatings: 150,
    }
},
{
    type: "restaurant",
    data: {
        type: "F",
        id: "789012",
        name: "Burger Lab",
        uuid: "def456-7890-ghij-slmn-opqrseuvwx",
        city: "2",
        area: "Downtown",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "https://play-lh.googleusercontent.com/soPvnOP8W0BRDPfqJPZB577ATZj44sjTqzp-STXq9iRNDKu0rgAmq49xikglqrUE7N4",
        cuisines: ["Burger", "Pizza"],
        tags: [],
        costForTwo: 1200,
        costForTwoString: "₹1200 for two",
        deliveryTime: 40,
        minDeliveryTime: 35,
        maxDeliveryTime: 45,
        lastMileTravel: 4.0,
        slugs: {
            restaurant: "sushi-world-downtown",
            city: "newyork"
        },
        cityState: "2",
        address: "303, Sushi Street, Downtown, New York",
        locality: "Downtown",
        parentId: 678901,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        avgRating: "3.9",
        totalRatings: 150,
    }
},

]

export default resList;